### ISSUE TITLE
I can't find the datasets(.h5),have you provided ?

### ISSUE THREAD

**Issue by cn784** [aigc-apps/AMFormer#1]
thank you for your applying if you see this question.

**Comment by Ch3ngY1** [comment]
There is no data differences between the .h5 files and official .csv files, I manually transferred them into .h5 to speed up data loading process. To create H5 datasets, you can refer to the official documentation for the process.

**Comment by Cgetier520990** [comment]
> thank you for your applying if you see this question.

请问你复现完了吗？我出现  File "D:\anaconda\envs\AMFormer\Lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 278: illegal multibyte sequence
的报错，你有遇到过吗？
