### ISSUE TITLE
main.py中的data_load问题

### ISSUE THREAD

**Issue by Cgetier520990** [aigc-apps/AMFormer#14]
![image](https://github.com/user-attachments/assets/c4240415-5060-472e-a995-d61bb4c5d86b)
这里的data_load是不是有问题，首先getattr(),传入的不应该是一个实例化对象吗？这里是啥？

**Comment by Ch3ngY1** [comment]
from utils import data_load，这里的getattr就是从这个data_load里根据后面的名称去取对应的数据class，对应关系就是在utils/data_load/__init__.py这里定义的

**Comment by Cgetier520990** [comment]
嗯嗯，我之前是直接运行的main.py，可能里面的参数没有覆盖，导致这部分有问题，如果我没猜错的话，这里应该找的DataSet类？

**Comment by Ch3ngY1** [comment]
是的，在data_hcdr里MyDataset类也是继承torch.utils.data.Dataset类的
