### ISSUE TITLE
想请教您一个关于数据载入的问题

### ISSUE THREAD

**Issue by 18970115041** [aigc-apps/AMFormer#15]
我的数据是 样本个数*特征个数（600个特征，均为连续数据） 的csv文件，想要进行一个回归任务（Lable是>0的数值），但是发现模拟数据载入一直报错（RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)），您能帮忙解答下需要如何进行我的数据载入吗？
![Uploading question.png…]()

**Comment by 18970115041** [comment]
![Uploading question.png…]()

**Comment by 18970115041** [comment]
![Uploading question.png…]()

**Comment by 18970115041** [comment]
![question](https://github.com/user-attachments/assets/8707e90d-b77e-43b0-841e-d21a142141d0)

**Comment by Ch3ngY1** [comment]
可以参考以下代码，dim必须是heads的整数倍
```


class args():
    def __init__(self):
        self.dim = 16
        self.depth = 3
        self.heads = 8
        self.attn_dropout = 0.2
        self.ff_dropout = 0.1
        self.use_cls_token = True
        self.groups = [120, 120, 120]
        self.sum_num_per_group = [32, 32, 32]
        self.prod_num_per_group = [6, 6, 6]
        self.cluster = True
        self.target_mode = 'mix'
        self.token_descent = False #True,
        self.use_prod = True
        self.num_special_tokens = 2
        self.categories = []
        self.num_unique_categories = 1
        self.out = 1
        self.num_cont = 600
        self.num_cate = 0
        self.use_sigmoid = True
        self.qk_relu = False

import torch
batch_size = 32
channel_cont = 600
channel_cate = 0
time = 32
num_classes = 1
input_data_cont = torch.rand(batch_size, channel_cont)
input_data_cate = torch.rand(batch_size, channel_cate)
input_data3 = torch.rand(batch_size)
from models.AM_Former import FTTransformer
args = args()
model = FTTransformer(args)
outputs = model(input_data_cate, input_data_cont, input_data3)
print(outputs)
```

**Comment by 18970115041** [comment]
> 可以参考以下代码，dim必须是heads的整数倍
> 
> ```
> 
> 
> class args():
>     def __init__(self):
>         self.dim = 16
>         self.depth = 3
>         self.heads = 8
>         self.attn_dropout = 0.2
>         self.ff_dropout = 0.1
>         self.use_cls_token = True
>         self.groups = [120, 120, 120]
>         self.sum_num_per_group = [32, 32, 32]
>         self.prod_num_per_group = [6, 6, 6]
>         self.cluster = True
>         self.target_mode = 'mix'
>         self.token_descent = False #True,
>         self.use_prod = True
>         self.num_special_tokens = 2
>         self.categories = []
>         self.num_unique_categories = 1
>         self.out = 1
>         self.num_cont = 600
>         self.num_cate = 0
>         self.use_sigmoid = True
>         self.qk_relu = False
> 
> import torch
> batch_size = 32
> channel_cont = 600
> channel_cate = 0
> time = 32
> num_classes = 1
> input_data_cont = torch.rand(batch_size, channel_cont)
> input_data_cate = torch.rand(batch_size, channel_cate)
> input_data3 = torch.rand(batch_size)
> from models.AM_Former import FTTransformer
> args = args()
> model = FTTransformer(args)
> outputs = model(input_data_cate, input_data_cont, input_data3)
> print(outputs)
> ```

好的，非常感谢您的帮助！
