### ISSUE TITLE
请问程序中的topk是否对应的是网络架构图中的top-k

### ISSUE THREAD

**Issue by hzwz0203** [aigc-apps/AMFormer#16]
想请问下大佬，top-k不是要取k个最大值吗，我看程序中直接赋值-1，不懂是什么意思
![微信图片_20241009210247](https://github.com/user-attachments/assets/ffc4d4ee-f876-497f-b9dd-9ddc1410dac9)

**Comment by Ch3ngY1** [comment]
这个Attention好像是废弃了的，模型定义里用的是MemoryBlock这个class，你可以看一下这个类的定义

**Comment by hzwz0203** [comment]
> 这个Attention好像是废弃了的，模型定义里用的是MemoryBlock这个类，你可以看一下这个类的定义

好的，我重新去看了MemoryBlock这个类，有关top-k的定义是else语句下的num_per_group吗，如果不是，请问是哪个哈
![image](https://github.com/user-attachments/assets/581c63ea-6306-4192-adf9-cab154bda53d)

**Comment by Ch3ngY1** [comment]
是的 就是这个参数
