### ISSUE TITLE
h5数据集以及格式问题

### ISSUE THREAD

**Issue by Wingleaves** [aigc-apps/AMFormer#19]
您好，在运行代码时，我发现代码对dataset格式有要求，请问您可以提供/home/ceyu.cy2/datasets/tabular/Credit/application_train.h5这里的h5文件嘛？或者给出h5文件的结构？十分感谢！

**Comment by Ch3ngY1** [comment]
数据类型是一个 样本量 * 特征数 的一个numpy array
如果你需要直接使用自己的数据，可以直接从模型文件AM_Former.py的242行开始处理，前面放你自己的数据处理流程即可，得到一个BS * Feature_num * dim的tensor即可
