### ISSUE TITLE
关于使用其他数据集训练的问题

### ISSUE THREAD

**Issue by ZZC2002ZZC** [aigc-apps/AMFormer#2]
尊敬的作者您好：
       我想尝试用您的模型进行多分类任务，该怎么运作。

**Comment by Ch3ngY1** [comment]
config/datasets/中的yaml文件里有个out参数，把out参数设置成你最终的分类结果数量就能完成多分类，然后根据数据集设置对应的categories即可

**Comment by ZZC2002ZZC** [comment]
谢谢您的回复，想问下在哪里加载数据集的路径呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月24日(周三) 中午11:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [aigc-apps/AMFormer] 关于使用其他数据集训练的问题 (Issue #2)




 
config/datasets/中的yaml文件里有个out参数，把out参数设置成你最终的分类结果数量就能完成多分类，然后根据数据集设置对应的categories即可

**Comment by Ch3ngY1** [comment]
可以参考utils/data_load/data_hcdr.py，这边写的是固定的路径，因为不同数据集的处理方式不同，就直接写在data_load模块中了

**Comment by jianghai1999** [comment]
尊敬的作者您好：
不好意思，打扰您了，请问一下，如果用来做回归预测，除了修改out参数输出为1以外，还需要修改那些参数呢？

**Comment by Ch3ngY1** [comment]
@jianghai1999 根据你具体的数据集设置categories，这部分主要是为了把类别数据用于之后的embedding，如果你已经完成了embedding可以不管这一部分，直接输入到模型的特征提取部分就行了

**Comment by waterha** [comment]
作者您好，请问源码中data_hcdr.py中 class make_split()模块中的file 和 root 代表什么
