### ISSUE TITLE
你好 我运行你程序报错少了model_name 但代码中我确实没有找到model_name 请问这是什么原因

### ISSUE THREAD

**Issue by dianasoul** [aigc-apps/AMFormer#4]
![微信截图_20240724141658](https://github.com/user-attachments/assets/a9291dc3-290f-4827-b324-fc97cd411170)

**Comment by Ch3ngY1** [comment]
python main.py --config config/run/ours_fttrans-hcdr.yaml

**Comment by Ch3ngY1** [comment]
python main.py --config config/run/ours_fttrans-hcdr.yaml
