### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by Chacura** [aigc-apps/AMFormer#5]
麻烦能问一下作者的数据集来源吗，没有数据集跑不起来吧，谢谢

**Comment by Ch3ngY1** [comment]
数据来源都是公开的数据集，具体可以参考论文section 5.1里的介绍，下载路径在参考文献中也能获取到

**Comment by Cgetier520990** [comment]
> 麻烦能问一下作者的数据集来源吗，没有数据集跑不起来吧，谢谢

你好，你找的数据集了吗？我看到作者参考文献里面的路径，没找到，有的网址打不开，kaggle的那个网址怪怪的

**Comment by Cgetier520990** [comment]
> 麻烦能问一下作者的数据集来源吗，没有数据集跑不起来吧，谢谢

![image](https://github.com/user-attachments/assets/c26b2329-7e05-4f32-8ec4-8aa9d3517f90)
你好这里的data_load是不是有问题啊？总是出现一下的报错，你有复现出来吗？
AttributeError: module 'utils.data_load' has no attribute 'evaluate'

**Comment by Chacura** [comment]
数据集我也没找全部的，只找那个什么信用卡风险评估的但是好像也不太匹配，最后我也是把模型单独拿出来然后写训练和测试代码跑的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月8日(星期天) 下午3:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aigc-apps/AMFormer] 数据集 (Issue #5)














  
麻烦能问一下作者的数据集来源吗，没有数据集跑不起来吧，谢谢
  
你好，你找的数据集了吗？我看到作者参考文献里面的路径，没找到，有的网址打不开，kaggle的那个网址怪怪的

**Comment by Cgetier520990** [comment]
> 数据集我也没找全部的，只找那个什么信用卡风险评估的但是好像也不太匹配，最后我也是把模型单独拿出来然后写训练和测试代码跑的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年9月8日(星期天) 下午3:33 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [aigc-apps/AMFormer] 数据集 (Issue #5) 麻烦能问一下作者的数据集来源吗，没有数据集跑不起来吧，谢谢 你好，你找的数据集了吗？我看到作者参考文献里面的路径，没找到，有的网址打不开，kaggle的那个网址怪怪的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

啥！自己写的训练和测试代码，好小众的词汇啊，好厉害呀。我也在kaggle找了homecredit那个数据集，但是报错很多，能认识一下您，分享一下你复现的项目吗？我导已经催的，诶，一言难尽，我都准备放弃这份代码了，我想看看，大佬是怎么能把模型拿出来，然后自己写的。我不会这些，每次复现都是这样。

**Comment by Chacura** [comment]
我也就是自己随便弄了弄，深度学习模型训练测试不都是基本上那几行代码嘛，用这个模型做了个二分类的问题。要单独拿出来用的话就是初始化一些参数，然后训练就行了。我代码写的也不咋地，也只能给你参考参考了，不介意的话就看一下这个吧，我发给你




------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月9日(星期一) 中午11:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aigc-apps/AMFormer] 数据集 (Issue #5)














  
数据集我也没找全部的，只找那个什么信用卡风险评估的但是好像也不太匹配，最后我也是把模型单独拿出来然后写训练和测试代码跑的
 …
 ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2024年9月8日(星期天) 下午3:33 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [aigc-apps/AMFormer] 数据集 (Issue #5) 麻烦能问一下作者的数据集来源吗，没有数据集跑不起来吧，谢谢 你好，你找的数据集了吗？我看到作者参考文献里面的路径，没找到，有的网址打不开，kaggle的那个网址怪怪的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
啥！自己写的训练和测试代码，好小众的词汇啊，好厉害呀。我也在kaggle找了homecredit那个数据集，但是报错很多，能认识一下您，分享一下你复现的项目吗？我导已经催的，诶，一言难尽，我都准备放弃这份代码了，我想看看，大佬是怎么能把模型拿出来，然后自己写的。我不会这些，每次复现都是这样。

**Comment by Cgetier520990** [comment]
> 我也就是自己随便弄了弄，深度学习模型训练测试不都是基本上那几行代码嘛，用这个模型做了个二分类的问题。要单独拿出来用的话就是初始化一些参数，然后训练就行了。我代码写的也不咋地，也只能给你参考参考了，不介意的话就看一下这个吧，我发给你
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年9月9日(星期一) 中午11:16 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [aigc-apps/AMFormer] 数据集 (Issue #5) 数据集我也没找全部的，只找那个什么信用卡风险评估的但是好像也不太匹配，最后我也是把模型单独拿出来然后写训练和测试代码跑的 … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2024年9月8日(星期天) 下午3:33 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [aigc-apps/AMFormer] 数据集 (Issue #5) 麻烦能问一下作者的数据集来源吗，没有数据集跑不起来吧，谢谢 你好，你找的数据集了吗？我看到作者参考文献里面的路径，没找到，有的网址打不开，kaggle的那个网址怪怪的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 啥！自己写的训练和测试代码，好小众的词汇啊，好厉害呀。我也在kaggle找了homecredit那个数据集，但是报错很多，能认识一下您，分享一下你复现的项目吗？我导已经催的，诶，一言难尽，我都准备放弃这份代码了，我想看看，大佬是怎么能把模型拿出来，然后自己写的。我不会这些，每次复现都是这样。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

好嘞，谢谢您，十分感谢，您看您怎么发给我嘞？我微信号：Cgetier520990

**Comment by Chacura** [comment]
我邮箱附件发过去了没有嘛



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月9日(星期一) 中午12:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aigc-apps/AMFormer] 数据集 (Issue #5)














  
我也就是自己随便弄了弄，深度学习模型训练测试不都是基本上那几行代码嘛，用这个模型做了个二分类的问题。要单独拿出来用的话就是初始化一些参数，然后训练就行了。我代码写的也不咋地，也只能给你参考参考了，不介意的话就看一下这个吧，我发给你
 …
 ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2024年9月9日(星期一) 中午11:16 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [aigc-apps/AMFormer] 数据集 (Issue #5) 数据集我也没找全部的，只找那个什么信用卡风险评估的但是好像也不太匹配，最后我也是把模型单独拿出来然后写训练和测试代码跑的 … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2024年9月8日(星期天) 下午3:33 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [aigc-apps/AMFormer] 数据集 (Issue #5) 麻烦能问一下作者的数据集来源吗，没有数据集跑不起来吧，谢谢 你好，你找的数据集了吗？我看到作者参考文献里面的路径，没找到，有的网址打不开，kaggle的那个网址怪怪的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 啥！自己写的训练和测试代码，好小众的词汇啊，好厉害呀。我也在kaggle找了homecredit那个数据集，但是报错很多，能认识一下您，分享一下你复现的项目吗？我导已经催的，诶，一言难尽，我都准备放弃这份代码了，我想看看，大佬是怎么能把模型拿出来，然后自己写的。我不会这些，每次复现都是这样。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
好嘞，谢谢您，十分感谢，您看您怎么发给我嘞？我微信号：Cgetier520990

**Comment by Cgetier520990** [comment]
> 我邮箱附件发过去了没有嘛
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年9月9日(星期一) 中午12:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [aigc-apps/AMFormer] 数据集 (Issue #5) 我也就是自己随便弄了弄，深度学习模型训练测试不都是基本上那几行代码嘛，用这个模型做了个二分类的问题。要单独拿出来用的话就是初始化一些参数，然后训练就行了。我代码写的也不咋地，也只能给你参考参考了，不介意的话就看一下这个吧，我发给你 … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2024年9月9日(星期一) 中午11:16 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [aigc-apps/AMFormer] 数据集 (Issue #5) 数据集我也没找全部的，只找那个什么信用卡风险评估的但是好像也不太匹配，最后我也是把模型单独拿出来然后写训练和测试代码跑的 … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2024年9月8日(星期天) 下午3:33 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [aigc-apps/AMFormer] 数据集 (Issue #5) 麻烦能问一下作者的数据集来源吗，没有数据集跑不起来吧，谢谢 你好，你找的数据集了吗？我看到作者参考文献里面的路径，没找到，有的网址打不开，kaggle的那个网址怪怪的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 啥！自己写的训练和测试代码，好小众的词汇啊，好厉害呀。我也在kaggle找了homecredit那个数据集，但是报错很多，能认识一下您，分享一下你复现的项目吗？我导已经催的，诶，一言难尽，我都准备放弃这份代码了，我想看看，大佬是怎么能把模型拿出来，然后自己写的。我不会这些，每次复现都是这样。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 好嘞，谢谢您，十分感谢，您看您怎么发给我嘞？我微信号：Cgetier520990 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
![image](https://github.com/user-attachments/assets/f21c3dd9-e915-4053-b501-f1205bb02951)
我没看到任何附件诶
![image](https://github.com/user-attachments/assets/b0486b1a-1d80-4707-803a-fdb2d3191fc1)

**Comment by Cgetier520990** [comment]
> 我邮箱附件发过去了没有嘛
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年9月9日(星期一) 中午12:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [aigc-apps/AMFormer] 数据集 (Issue #5) 我也就是自己随便弄了弄，深度学习模型训练测试不都是基本上那几行代码嘛，用这个模型做了个二分类的问题。要单独拿出来用的话就是初始化一些参数，然后训练就行了。我代码写的也不咋地，也只能给你参考参考了，不介意的话就看一下这个吧，我发给你 … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2024年9月9日(星期一) 中午11:16 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [aigc-apps/AMFormer] 数据集 (Issue #5) 数据集我也没找全部的，只找那个什么信用卡风险评估的但是好像也不太匹配，最后我也是把模型单独拿出来然后写训练和测试代码跑的 … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2024年9月8日(星期天) 下午3:33 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [aigc-apps/AMFormer] 数据集 (Issue #5) 麻烦能问一下作者的数据集来源吗，没有数据集跑不起来吧，谢谢 你好，你找的数据集了吗？我看到作者参考文献里面的路径，没找到，有的网址打不开，kaggle的那个网址怪怪的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 啥！自己写的训练和测试代码，好小众的词汇啊，好厉害呀。我也在kaggle找了homecredit那个数据集，但是报错很多，能认识一下您，分享一下你复现的项目吗？我导已经催的，诶，一言难尽，我都准备放弃这份代码了，我想看看，大佬是怎么能把模型拿出来，然后自己写的。我不会这些，每次复现都是这样。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 好嘞，谢谢您，十分感谢，您看您怎么发给我嘞？我微信号：Cgetier520990 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

<936551247@qq.com>这是我的邮箱，您可以直接发一份，不通过github吗？
